[pytest]
addopts =
    -v
    --alluredir=allure-results


markers =
    smoke: smoke tests
    regress: regression tests
    test_case_id(id): binding a test to a test case ID from Azure DevOps
    test_task_id(id): binding a test to a task ID from Azure DevOps
    test_script_runs: marking for all script runs
    test_scripts_suites_es_assets: mark scripts for class TestEsAssetsScriptSuite
    test_scripts_suites_es_asset_types: mark scripts for class TestEsAssetTypesScriptSuite
    test_scripts_suites_es_asset_templates: mark scripts for class TestEsAssetTemplatesScriptSuite
    test_scripts_suites_es_asset_template_attachments: mark scripts for class TestEsAssetTemplateAttachmentsScriptSuite
    test_scripts_suites_es_asset_template_attributes: mark scripts for class TestEsAssetTemplateAttributesScriptSuite
    test_scripts_suites_es_asset_template_districts: mark scripts for class TestEsAssetTemplateDistrictsScriptSuite
    test_scripts_suites_es_asset_template_skills: mark scripts for class TestEsAssetTemplateSkillsScriptSuite
    test_scripts_suites_es_asset_template_work_types: mark scripts for class TestEsAssetTemplateWorkTypesScriptSuite
    test_scripts_suites_es_companies: mark scripts for class TestEsCompaniesScriptSuite
    test_scripts_suites_es_company_attachments: mark scripts for class TestEsCompanyAttachmentsScriptSuite
    test_scripts_suites_es_companies_attributes: mark scripts for class TestEsCompanyAttributesScriptSuite
    test_scripts_suites_es_companies_bank_accounts: mark scripts for class TestEsCompaniesBankAccountsScriptSuite
    test_scripts_suites_es_companies_contacts: mark scripts for class TestEsCompaniesContactsScriptSuite
    test_scripts_suites_es_company_locations: mark scripts for class TestEsCompanyLocationsScriptSuite
    test_scripts_suites_es_districts: mark scripts for class TestEsDistrictsScriptSuite
    test_scripts_suites_es_locations: mark scripts for class TestEsLocationsScriptSuite
    PA: all tests under tests/PA
    ADM: all tests under tests/ADM
    AUTH: all tests under tests/AUTH
    AUTHN: all tests under tests/AUTHN
    AUTHZ: all tests under tests/AUTHZ
    COMMON: all tests under tests/COMMON
    ES: all tests under tests/ES
    EXPORT: all tests under tests/EXPORT
    MSG: all tests under tests/MSG
    PMP: all tests under tests/PMP
    SC: all tests under tests/SC
    TSTG: all tests under tests/TSTG
    WH: all tests under tests/WH
    WORK: all tests under tests/WORK

