[pytest]
addopts =
    -v
    --alluredir=allure-results
    --reruns 2
    --reruns-delay 4


markers =
    smoke: smoke tests
    regress: regression tests
    ng: negative tests
    test_case_id(id): binding a test to a test case ID from Azure DevOps
    test_task_id(id): binding a test to a task ID from Azure DevOps
    test_script_runs: marking for all script runs
    test_scripts_suites_es_assets: mark scripts for class TestEsAssetsScriptSuite
    test_scripts_suites_es_asset_types: mark scripts for class TestEsAssetTypesScriptSuite
    test_scripts_suites_es_asset_templates: mark scripts for class TestEsAssetTemplatesScriptSuite
    test_scripts_suites_es_asset_template_attachments: mark scripts for class TestEsAssetTemplateAttachmentsScriptSuite
    test_scripts_suites_es_asset_template_attributes: mark scripts for class TestEsAssetTemplateAttributesScriptSuite
    test_scripts_suites_es_asset_template_districts: mark scripts for class TestEsAssetTemplateDistrictsScriptSuite
    test_scripts_suites_es_asset_template_skills: mark scripts for class TestEsAssetTemplateSkillsScriptSuite
    test_scripts_suites_es_asset_template_work_types: mark scripts for class TestEsAssetTemplateWorkTypesScriptSuite
    test_scripts_suites_es_companies: mark scripts for class TestEsCompaniesScriptSuite
    test_scripts_suites_es_company_attachments: mark scripts for class TestEsCompanyAttachmentsScriptSuite
    test_scripts_suites_es_companies_attributes: mark scripts for class TestEsCompanyAttributesScriptSuite
    test_scripts_suites_es_companies_bank_accounts: mark scripts for class TestEsCompaniesBankAccountsScriptSuite
    test_scripts_suites_es_companies_contacts: mark scripts for class TestEsCompaniesContactsScriptSuite
    test_scripts_suites_es_company_locations: mark scripts for class TestEsCompanyLocationsScriptSuite
    test_scripts_suites_es_districts: mark scripts for class TestEsDistrictsScriptSuite
    test_scripts_suites_es_locations: mark scripts for class TestEsLocationsScriptSuite
    HubEx.Service.ADM.Api: all tests under tests/ADM
    HubEx.Service.AUTH.Api: all tests under tests/AUTH
    HubEx.Service.AUTHN.Api: all tests under tests/AUTHN
    HubEx.Service.AUTHZ.Api: all tests under tests/AUTHZ
    HubEx.Service.CM.Api: all tests under tests/CM
    HubEx.Service.COMMON.Api: all tests under tests/COMMON
    HubEx.Service.ES.Api: all tests under tests/ES
    HubEx.Service.EXPORT.Api: all tests under tests/EXPORT
    HubEx.Service.IMPORT.Api: all tests under tests/IMPORT
    HubEx.Service.LIC.Api: all tests under tests/LIC
    HubEx.Service.MSG.Api: all tests under tests/MSG
    HubEx.Service.NEWS.Api: all tests under tests/NEWS
    HubEx.Service.PA.Api: all tests under tests/PA
    HubEx.Service.PMP.Api: all tests under tests/PMP
    HubEx.Service.PROXY.Api: all tests under tests/PROXY
    HubEx.Service.REPORT.Api: all tests under tests/REPORT
    HubEx.Service.SC.Api: all tests under tests/SC
    HubEx.Service.SLA.Api: all tests under tests/SLA
    HubEx.Service.TSTG.Api: all tests under tests/TSTG
    HubEx.Service.UI.Api: all tests under tests/UI
    HubEx.Service.WH.Api: all tests under tests/WH
    HubEx.Service.WORK.Api: all tests under tests/WORK
    HubEx.Service.WSP.Api: all tests under tests/WSP
    HubEx.Service.RT.Api: all tests under tests/RT
    HubEx.ApiGateway: all tests under tests/GW